; MSUTRKS.INC
; Generates MSU-1 track number equates.
; Copyright (c) 2025 Sunlit
; Released under the MIT License
;
; Please credit me if you use this code in your software or make any derivatives of this code.
; It was a pain to write, and it would be greatly appreciated if you did!
; It's not like you have to pay me or anything. Crediting me is free.

;###################
;# MSU-1 TRACK IDS #
;###################

	msutrack	intro,0 ; sample track definitions
	msutrack	title,1

; EOF